import { IMG } from "./images";
import type { Locality, Project, Property } from "./types";

/**
 * Launch micro-market: Jaipur (spec §121–122 — start with one city and a
 * handful of high-demand localities). Mock inventory until the listings API ships.
 */

export const LOCALITIES: Locality[] = [
  { slug: "malviya-nagar", name: "Malviya Nagar", city: "Jaipur", image: IMG.patrikaGate, avgPriceSqft: 6200, yoy: 7.4, rentFrom: 14000, listings: 412, tagline: "Established, central, metro-connected" },
  { slug: "vaishali-nagar", name: "Vaishali Nagar", city: "Jaipur", image: IMG.societyGarden, avgPriceSqft: 5800, yoy: 6.1, rentFrom: 13000, listings: 356, tagline: "Family neighbourhood with great schools" },
  { slug: "c-scheme", name: "C-Scheme", city: "Jaipur", image: IMG.jaipurStreet, avgPriceSqft: 11400, yoy: 5.2, rentFrom: 28000, listings: 128, tagline: "Premium addresses in the city core" },
  { slug: "jagatpura", name: "Jagatpura", city: "Jaipur", image: IMG.township, avgPriceSqft: 4300, yoy: 9.8, rentFrom: 9500, listings: 521, tagline: "Fast-growing, new-project corridor" },
  { slug: "mansarovar", name: "Mansarovar", city: "Jaipur", image: IMG.apartmentBlock, avgPriceSqft: 5100, yoy: 6.8, rentFrom: 11000, listings: 603, tagline: "Large, well-planned residential hub" },
  { slug: "ajmer-road", name: "Ajmer Road", city: "Jaipur", image: IMG.townshipLawn, avgPriceSqft: 3400, yoy: 11.2, rentFrom: 8000, listings: 287, tagline: "Plots and townships on the growth axis" },
];

/** Data period for all locality price intelligence (spec §26 — never show numbers without time context). */
export const PRICE_DATA_PERIOD = "Apr – Sep 2026 · updated 22 Sep 2026";

export const PROPERTIES: Property[] = [
  {
    slug: "3-bhk-apartment-malviya-nagar-jaipur",
    title: "Sunlit 3 BHK with park view",
    kind: "Apartment", intent: "buy", price: 8_900_000, priceIsMonthly: false,
    bhk: 3, baths: 3, areaSqft: 1650, city: "Jaipur", locality: "Malviya Nagar", map: { x: 58, y: 56 },
    availability: "Ready to Move", furnishing: "Semi-furnished", floor: "6 of 12", facing: "East", ageYears: 3, parking: 2,
    project: "Aravali Heights", seller: { type: "Owner", name: "Rakesh Agarwal", responseTime: "Usually replies in 1 hr" },
    verified: true, rera: "RAJ/P/2021/1432", featured: true, postedDaysAgo: 2,
    images: [IMG.apartmentPark, IMG.livingWarm, IMG.kitchen, IMG.bedroom, IMG.livingBright], hasVideo: true, hasFloorPlan: true,
    amenities: ["Lift", "Power backup", "Gym", "Clubhouse", "Covered parking", "24×7 security", "Children's play area", "Rainwater harvesting"],
    highlights: ["Park-facing living room", "Cross ventilation", "5 min to Malviya Nagar metro", "Modular kitchen"],
    description: "A bright, east-facing 3 BHK on the 6th floor of Aravali Heights. The living room opens onto a wide balcony overlooking the central park, and every bedroom has cross ventilation. Two covered parking slots, modular kitchen and wardrobes are included.",
  },
  {
    slug: "4-bhk-villa-c-scheme-jaipur",
    title: "Courtyard villa in C-Scheme",
    kind: "Villa", intent: "buy", price: 42_500_000, priceIsMonthly: false,
    bhk: 4, baths: 5, areaSqft: 4200, city: "Jaipur", locality: "C-Scheme", map: { x: 47, y: 38 },
    availability: "Ready to Move", furnishing: "Fully furnished", facing: "North", ageYears: 6, parking: 3,
    seller: { type: "Agent", name: "Heritage Realty", certified: true, responseTime: "Usually replies in 30 min" },
    verified: true, postedDaysAgo: 5,
    images: [IMG.heroVilla, IMG.livingLounge, IMG.kitchen, IMG.bedroom, IMG.livingDining], hasVideo: true, hasFloorPlan: true,
    amenities: ["Private garden", "Swimming pool", "Home automation", "Servant quarter", "Solar", "CCTV"],
    highlights: ["Central courtyard with water body", "Private pool", "Walking distance to SMS Stadium"],
    description: "A contemporary courtyard villa on a quiet lane in C-Scheme. Double-height living, a private pool and a landscaped rear garden. Sold fully furnished with home automation.",
  },
  {
    slug: "2-bhk-apartment-jagatpura-jaipur",
    title: "Compact 2 BHK near EC road",
    kind: "Apartment", intent: "buy", price: 3_850_000, priceIsMonthly: false,
    bhk: 2, baths: 2, areaSqft: 1080, city: "Jaipur", locality: "Jagatpura", map: { x: 72, y: 70 },
    availability: "Under Construction", furnishing: "Unfurnished", floor: "4 of 14", facing: "North-East", parking: 1,
    project: "Orchid Greens", seller: { type: "Builder", name: "Orchid Developers" },
    verified: true, rera: "RAJ/P/2024/2981", postedDaysAgo: 1,
    images: [IMG.underConstruction, IMG.livingBright, IMG.kitchen, IMG.bedroom], hasFloorPlan: true,
    amenities: ["Lift", "Clubhouse", "Jogging track", "Power backup", "Gated community"],
    highlights: ["Possession Dec 2027", "Construction-linked plan", "Near JECRC & Mahal Road"],
    description: "Efficient 2 BHK in Orchid Greens, a 6-tower gated project on the Jagatpura growth corridor. Possession December 2027 with a construction-linked payment plan.",
  },
  {
    slug: "3-bhk-builder-floor-vaishali-nagar-jaipur",
    title: "Independent floor with terrace",
    kind: "Builder Floor", intent: "buy", price: 6_400_000, priceIsMonthly: false,
    bhk: 3, baths: 3, areaSqft: 1800, city: "Jaipur", locality: "Vaishali Nagar", map: { x: 24, y: 40 },
    availability: "Ready to Move", furnishing: "Semi-furnished", floor: "2 of 3", facing: "West", ageYears: 1, parking: 1,
    seller: { type: "Owner", name: "Sunita Mehra", responseTime: "Usually replies in 2 hrs" },
    verified: false, postedDaysAgo: 9,
    images: [IMG.builderFloor, IMG.livingDining, IMG.bedroom], hasFloorPlan: false,
    amenities: ["Private terrace", "Covered parking", "Water storage"],
    highlights: ["Private terrace access", "Brand new construction", "Near Amrapali Circle"],
    description: "A newly built independent second floor with private terrace rights, in a quiet sector of Vaishali Nagar close to Amrapali Circle.",
  },
  {
    slug: "2-bhk-apartment-for-rent-malviya-nagar-jaipur",
    title: "Furnished 2 BHK for families",
    kind: "Apartment", intent: "rent", price: 22_000, priceIsMonthly: true, deposit: 66_000,
    bhk: 2, baths: 2, areaSqft: 1150, city: "Jaipur", locality: "Malviya Nagar", map: { x: 61, y: 60 },
    availability: "Available Now", furnishing: "Fully furnished", floor: "3 of 8", facing: "East", parking: 1,
    seller: { type: "Owner", name: "Vivek Sharma", responseTime: "Usually replies in 1 hr" },
    verified: true, postedDaysAgo: 0,
    images: [IMG.livingWarm, IMG.bedroom, IMG.kitchen, IMG.societyGarden],
    amenities: ["Lift", "Power backup", "Wi-Fi ready", "Security", "Visitor parking"],
    highlights: ["Preferred: families", "Move in immediately", "Metro 700 m"],
    description: "Well-kept, fully furnished 2 BHK — beds, wardrobes, fridge, washing machine and ACs in both bedrooms. Families preferred. Minimum lease 11 months.",
  },
  {
    slug: "1-bhk-studio-for-rent-c-scheme-jaipur",
    title: "Designer studio in the city core",
    kind: "Apartment", intent: "rent", price: 16_500, priceIsMonthly: true, deposit: 33_000,
    bhk: 1, baths: 1, areaSqft: 620, city: "Jaipur", locality: "C-Scheme", map: { x: 45, y: 42 },
    availability: "Available from Nov", furnishing: "Fully furnished", floor: "5 of 7", facing: "South", parking: 1,
    seller: { type: "Agent", name: "UrbanNest Homes", certified: true, responseTime: "Usually replies in 20 min" },
    verified: true, postedDaysAgo: 3,
    images: [IMG.studio, IMG.livingBright, IMG.kitchen],
    amenities: ["Lift", "Gym", "Rooftop lounge", "Housekeeping"],
    highlights: ["Walk to Ashok Marg offices", "Housekeeping included", "Bachelors welcome"],
    description: "A compact, designer-finished studio with rooftop lounge access. Housekeeping twice a week is included in the rent.",
  },
  {
    slug: "3-bhk-house-for-rent-mansarovar-jaipur",
    title: "Independent house with garden",
    kind: "Independent House", intent: "rent", price: 32_000, priceIsMonthly: true, deposit: 96_000,
    bhk: 3, baths: 3, areaSqft: 2100, city: "Jaipur", locality: "Mansarovar", map: { x: 28, y: 72 },
    availability: "Available Now", furnishing: "Semi-furnished", facing: "North", parking: 2,
    seller: { type: "Owner", name: "Anil Kothari", responseTime: "Usually replies same day" },
    verified: true, postedDaysAgo: 6,
    images: [IMG.brickHouse, IMG.livingDining, IMG.bedroom],
    amenities: ["Front lawn", "Car porch", "Borewell", "Solar water heater"],
    highlights: ["Full house, no sharing", "Pets allowed", "Near Mansarovar metro"],
    description: "Full independent house with front lawn and porch for two cars in a quiet sector of Mansarovar. Pets allowed.",
  },
  {
    slug: "girls-pg-malviya-nagar-jaipur",
    title: "Nest Co-living for women",
    kind: "PG", intent: "pg", price: 9_500, priceIsMonthly: true, deposit: 9_500,
    areaSqft: 180, city: "Jaipur", locality: "Malviya Nagar", map: { x: 55, y: 62 },
    availability: "Available Now", furnishing: "Fully furnished",
    seller: { type: "Owner", name: "Nest Co-living", responseTime: "Usually replies in 15 min" },
    verified: true, postedDaysAgo: 2,
    images: [IMG.bedroom, IMG.studio, IMG.livingBright],
    amenities: ["Food included", "Wi-Fi", "AC", "Attached bathroom", "Housekeeping", "CCTV", "Laundry"],
    highlights: ["3 meals a day", "Biometric entry", "Near MNIT & malls"],
    description: "Safe, managed co-living for students and working women. Three home-style meals, daily housekeeping and biometric entry.",
    pg: { forGender: "Female", sharing: ["Single", "Double"], foodIncluded: true },
  },
  {
    slug: "boys-pg-jagatpura-jaipur",
    title: "Campus Stay near JECRC",
    kind: "PG", intent: "pg", price: 7_200, priceIsMonthly: true, deposit: 7_200,
    areaSqft: 160, city: "Jaipur", locality: "Jagatpura", map: { x: 76, y: 74 },
    availability: "Available Now", furnishing: "Fully furnished",
    seller: { type: "Agent", name: "StayEasy", certified: false },
    verified: false, postedDaysAgo: 11,
    images: [IMG.studio, IMG.bedroom],
    amenities: ["Food included", "Wi-Fi", "Study room", "Laundry"],
    highlights: ["Walk to JECRC", "Study room", "Double & triple sharing"],
    description: "Student-focused PG a short walk from JECRC with a quiet study room and breakfast + dinner included.",
    pg: { forGender: "Male", sharing: ["Double", "Triple"], foodIncluded: true },
  },
  {
    slug: "office-space-for-rent-c-scheme-jaipur",
    title: "Grade-A office on Ashok Marg",
    kind: "Office", intent: "commercial", price: 120_000, priceIsMonthly: true, deposit: 720_000,
    areaSqft: 2400, city: "Jaipur", locality: "C-Scheme", map: { x: 49, y: 35 },
    availability: "Available Now", furnishing: "Fully furnished", floor: "7 of 10", parking: 4,
    seller: { type: "Agent", name: "Workspace Partners", certified: true, responseTime: "Usually replies in 1 hr" },
    verified: true, featured: true, postedDaysAgo: 4,
    images: [IMG.office, IMG.apartmentModern],
    amenities: ["12 workstations", "2 cabins", "Reception", "Conference room", "Power backup", "Pantry"],
    highlights: ["Plug & play", "Metro 1.2 km", "Dedicated parking ×4"],
    description: "Plug-and-play office with 12 workstations, two cabins, a conference room and reception on Ashok Marg.",
  },
  {
    slug: "shop-for-sale-vaishali-nagar-jaipur",
    title: "Ground-floor shop, main road",
    kind: "Shop", intent: "commercial", price: 6_500_000, priceIsMonthly: false,
    areaSqft: 850, city: "Jaipur", locality: "Vaishali Nagar", map: { x: 21, y: 45 },
    availability: "Ready to Move", floor: "Ground", parking: 0,
    seller: { type: "Owner", name: "Deepak Jain" },
    verified: true, postedDaysAgo: 8,
    images: [IMG.shop, IMG.jaipurStreet],
    amenities: ["20 ft frontage", "Main road", "Washroom", "Visitor parking"],
    highlights: ["20 ft frontage", "High footfall", "Rental yield ~4%"],
    description: "Ground-floor retail unit on Vaishali Nagar main road with 20 ft frontage, ideal for a showroom or café.",
  },
  {
    slug: "residential-plot-ajmer-road-jaipur",
    title: "JDA-approved corner plot",
    kind: "Plot", intent: "plots", price: 5_400_000, priceIsMonthly: false,
    areaSqft: 1800, originalArea: { value: 200, unit: "sq.yd", region: "Rajasthan" },
    city: "Jaipur", locality: "Ajmer Road", map: { x: 12, y: 58 },
    availability: "Ready to Move", facing: "East",
    seller: { type: "Agent", name: "Landmark Estates", certified: true },
    verified: true, rera: "RAJ/P/2023/2210", postedDaysAgo: 3,
    images: [IMG.land, IMG.townshipLawn],
    amenities: ["Gated layout", "Boundary wall", "30 ft road", "Water & electricity", "Park facing"],
    highlights: ["Corner plot", "JDA approved", "30 ft wide road"],
    description: "East-facing corner plot in a gated JDA-approved layout off Ajmer Road with water and electricity connections in place.",
  },
  {
    slug: "agricultural-land-jagatpura-jaipur",
    title: "Farmland near Ring Road",
    kind: "Plot", intent: "plots", price: 18_000_000, priceIsMonthly: false,
    areaSqft: 108_900, originalArea: { value: 2.5, unit: "acre" },
    city: "Jaipur", locality: "Jagatpura", map: { x: 86, y: 82 },
    availability: "Ready to Move",
    seller: { type: "Owner", name: "Bhanwar Singh" },
    verified: false, postedDaysAgo: 15,
    images: [IMG.land],
    amenities: ["Borewell", "Road access", "Fenced"],
    highlights: ["2.5 acres", "Ring Road 3 km", "Clear title (owner stated)"],
    description: "Fenced agricultural land with borewell and road access, 3 km from the Ring Road.",
  },
  {
    slug: "4-bhk-penthouse-vaishali-nagar-jaipur",
    title: "Sky penthouse with private deck",
    kind: "Apartment", intent: "buy", price: 21_000_000, priceIsMonthly: false,
    bhk: 4, baths: 4, areaSqft: 3400, city: "Jaipur", locality: "Vaishali Nagar", map: { x: 26, y: 36 },
    availability: "Ready to Move", furnishing: "Semi-furnished", floor: "18 of 18", facing: "North-East", ageYears: 2, parking: 3,
    project: "The Crest", seller: { type: "Builder", name: "Crest Group" },
    verified: true, rera: "RAJ/P/2020/1102", featured: true, postedDaysAgo: 7,
    images: [IMG.apartmentTower, IMG.livingLounge, IMG.kitchen, IMG.bedroom, IMG.jaipurSkyline], hasVideo: true, hasFloorPlan: true,
    amenities: ["Private deck", "Jacuzzi", "Clubhouse", "Infinity pool", "Concierge", "EV charging"],
    highlights: ["Top-floor penthouse", "Private 600 sq.ft deck", "City skyline views"],
    description: "Top-floor penthouse at The Crest with a private 600 sq.ft deck, jacuzzi and uninterrupted skyline views.",
  },
  {
    slug: "3-bhk-villa-ajmer-road-jaipur",
    title: "Township villa with lawn",
    kind: "Villa", intent: "buy", price: 11_500_000, priceIsMonthly: false,
    bhk: 3, baths: 4, areaSqft: 2600, city: "Jaipur", locality: "Ajmer Road", map: { x: 16, y: 64 },
    availability: "Under Construction", furnishing: "Unfurnished", facing: "East", parking: 2,
    project: "Palm Meadows", seller: { type: "Builder", name: "Meadows Infra" },
    verified: true, rera: "RAJ/P/2025/3317", postedDaysAgo: 4,
    images: [IMG.villaRow, IMG.livingLounge, IMG.townhouses], hasFloorPlan: true,
    amenities: ["Clubhouse", "Lawn", "School in township", "Jogging track", "Gated community"],
    highlights: ["Possession Mar 2027", "Inside 120-acre township", "Private lawn"],
    description: "Duplex villa inside the 120-acre Palm Meadows township with a private lawn and access to the township school and clubhouse.",
  },
  {
    slug: "2-bhk-apartment-for-rent-jagatpura-jaipur",
    title: "Budget 2 BHK in gated society",
    kind: "Apartment", intent: "rent", price: 12_500, priceIsMonthly: true, deposit: 25_000,
    bhk: 2, baths: 2, areaSqft: 960, city: "Jaipur", locality: "Jagatpura", map: { x: 69, y: 76 },
    availability: "Available Now", furnishing: "Semi-furnished", floor: "8 of 12", facing: "West", parking: 1,
    seller: { type: "Owner", name: "Pooja Rathore" },
    verified: true, postedDaysAgo: 1,
    images: [IMG.apartmentBlock, IMG.livingDining, IMG.bedroom],
    amenities: ["Lift", "Gated community", "Power backup", "Park"],
    highlights: ["Low maintenance", "Near railway station", "Bachelors allowed"],
    description: "Semi-furnished 2 BHK with wardrobes and kitchen cabinets in a gated society close to Jagatpura station.",
  },
];

export const PROJECTS: Project[] = [
  { slug: "aravali-heights", name: "Aravali Heights", developer: "Aravali Group", locality: "Malviya Nagar", city: "Jaipur", image: IMG.apartmentPark, priceFrom: 6_200_000, priceTo: 12_500_000, configurations: "2, 3 & 4 BHK", status: "Ready to Move", possession: "Ready", rera: "RAJ/P/2021/1432", units: 340, acres: 6 },
  { slug: "orchid-greens", name: "Orchid Greens", developer: "Orchid Developers", locality: "Jagatpura", city: "Jaipur", image: IMG.underConstruction, priceFrom: 3_400_000, priceTo: 6_900_000, configurations: "2 & 3 BHK", status: "Under Construction", possession: "Dec 2027", rera: "RAJ/P/2024/2981", units: 612, acres: 9 },
  { slug: "palm-meadows", name: "Palm Meadows", developer: "Meadows Infra", locality: "Ajmer Road", city: "Jaipur", image: IMG.villaRow, priceFrom: 7_800_000, priceTo: 18_000_000, configurations: "3 & 4 BHK villas", status: "New Launch", possession: "Mar 2027", rera: "RAJ/P/2025/3317", units: 220, acres: 120 },
  { slug: "the-crest", name: "The Crest", developer: "Crest Group", locality: "Vaishali Nagar", city: "Jaipur", image: IMG.apartmentTower, priceFrom: 9_500_000, priceTo: 21_000_000, configurations: "3 & 4 BHK, penthouses", status: "Ready to Move", possession: "Ready", rera: "RAJ/P/2020/1102", units: 180, acres: 4 },
  { slug: "sanganer-square", name: "Sanganer Square", developer: "Pink City Builders", locality: "Mansarovar", city: "Jaipur", image: IMG.apartmentModern, priceFrom: 4_100_000, priceTo: 8_200_000, configurations: "2 & 3 BHK", status: "Upcoming", possession: "2028", rera: "Applied", units: 400, acres: 7 },
];

export function getProperty(slug: string): Property | undefined {
  return PROPERTIES.find((p) => p.slug === slug);
}

export function similarProperties(p: Property, limit = 3): Property[] {
  return PROPERTIES.filter((o) => o.slug !== p.slug && o.intent === p.intent)
    .sort((a, b) => score(b) - score(a))
    .slice(0, limit);

  function score(o: Property) {
    return (o.locality === p.locality ? 3 : 0) + (o.bhk === p.bhk ? 2 : 0) + (o.kind === p.kind ? 1 : 0);
  }
}
